In [3]:
import pandas as pd
train=pd.read_csv('train.csv')

In [7]:
train.describe()

Hazard         T1_V1         T1_V2         T1_V3        T1_V10  \
count  50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean       4.022785      9.722093     12.847585      3.186004      7.020451   
std        4.021194      5.167943      6.255743      1.739369      3.595279   
min        1.000000      1.000000      1.000000      1.000000      2.000000   
25%        1.000000      6.000000      7.000000      2.000000      3.000000   
50%        3.000000      9.000000     14.000000      3.000000      8.000000   
75%        5.000000     14.000000     18.000000      4.000000      8.000000   
max       69.000000     19.000000     24.000000      9.000000     12.000000   

             T1_V13        T1_V14         T2_V1         T2_V2         T2_V4  \
count  50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean      13.996255      1.578521     57.580051     12.419616     10.259495   
std        4.647499      0.862882     23.499818      4.783411      4.852008   
min        5.000000      0.000000      1.000000      1.000000      1.000000   
25%       10.000000      1.000000     40.000000      9.000000      6.000000   
50%       15.000000      1.000000     56.000000     11.000000     10.000000   
75%       20.000000      2.000000     77.000000     15.000000     14.000000   
max       20.000000      4.000000    100.000000     39.000000     22.000000   

              T2_V6         T2_V7         T2_V8         T2_V9        T2_V10  \
count  50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean       1.948215     33.487755      1.032236     12.493029      4.496520   
std        0.800117      5.834038      0.195893      7.314788      1.896717   
min        1.000000     22.000000      1.000000      1.000000      1.000000   
25%        2.000000     31.000000      1.000000      6.000000      3.000000   
50%        2.000000     34.000000      1.000000     14.000000      4.000000   
75%        2.000000     40.000000      1.000000     18.000000      6.000000   
max        7.000000     40.000000      3.000000     25.000000      7.000000   

             T2_V14        T2_V15  
count  50999.000000  50999.000000  
mean       2.451126      3.484480  
std        1.260074      3.076745  
min        1.000000      1.000000  
25%        2.000000      1.000000  
50%        2.000000      2.000000  
75%        3.000000      5.000000  
max        7.000000     12.000000

In [4]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
le.fit(train['T1_V4'])

LabelEncoder()

In [12]:
le.classes_

array(['B', 'C', 'E', 'G', 'H', 'N', 'S', 'W'], dtype=object)

In [15]:
train['T1_V4']=le.fit_transform(train['T1_V4'])

In [16]:
train.head()

Hazard  T1_V1  T1_V2  T1_V3  T1_V4 T1_V5 T1_V6 T1_V7 T1_V8 T1_V9   ...    \
Id                                                                     ...     
1        1     15      3      2      5     B     N     B     B     D   ...     
2        4     16     14      5      4     B     N     B     B     C   ...     
3        1     10     10      5      5     K     N     B     B     E   ...     
4        1     18     18      5      5     K     N     B     B     E   ...     
5        1     13     19      5      5     H     N     B     B     E   ...     

    T2_V6 T2_V7 T2_V8  T2_V9  T2_V10 T2_V11 T2_V12 T2_V13  T2_V14  T2_V15  
Id                                                                         
1       2    37     1     11       6      Y      N      E       2       2  
2       2    22     1     18       5      Y      Y      E       2       1  
3       6    37     2     14       6      Y      Y      E       6       1  
4       2    25     1      1       6      Y      N      C       2       6  
5       1    22     1      2       7      N      N      E       1       1  

[5 rows x 33 columns]

In [5]:
for i in range(train.shape[1]):
    if train.iloc[:,i].dtype=='O':
        train.iloc[:,i]=le.fit_transform(train.iloc[:,i])

In [6]:
train.describe()

Id        Hazard         T1_V1         T1_V2         T1_V3  \
count   50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean    50929.727897      4.022785      9.722093     12.847585      3.186004   
std     29314.685894      4.021194      5.167943      6.255743      1.739369   
min         1.000000      1.000000      1.000000      1.000000      1.000000   
25%     25660.500000      1.000000      6.000000      7.000000      2.000000   
50%     50977.000000      3.000000      9.000000     14.000000      3.000000   
75%     76268.500000      5.000000     14.000000     18.000000      4.000000   
max    101999.000000     69.000000     19.000000     24.000000      9.000000   

              T1_V4         T1_V5         T1_V6         T1_V7         T1_V8  \
count  50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean       3.352262      4.126042      0.440185      1.079433      1.089610   
std        2.403348      3.101243      0.496414      0.421798      0.449027   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        1.000000      1.000000      0.000000      1.000000      1.000000   
50%        5.000000      5.000000      0.000000      1.000000      1.000000   
75%        5.000000      8.000000      1.000000      1.000000      1.000000   
max        7.000000      9.000000      1.000000      3.000000      3.000000   

           ...              T2_V6         T2_V7         T2_V8         T2_V9  \
count      ...       50999.000000  50999.000000  50999.000000  50999.000000   
mean       ...           1.948215     33.487755      1.032236     12.493029   
std        ...           0.800117      5.834038      0.195893      7.314788   
min        ...           1.000000     22.000000      1.000000      1.000000   
25%        ...           2.000000     31.000000      1.000000      6.000000   
50%        ...           2.000000     34.000000      1.000000     14.000000   
75%        ...           2.000000     40.000000      1.000000     18.000000   
max        ...           7.000000     40.000000      3.000000     25.000000   

             T2_V10        T2_V11        T2_V12        T2_V13        T2_V14  \
count  50999.000000  50999.000000  50999.000000  50999.000000  50999.000000   
mean       4.496520      0.724328      0.182278      2.770956      2.451126   
std        1.896717      0.446857      0.386077      1.577206      1.260074   
min        1.000000      0.000000      0.000000      0.000000      1.000000   
25%        3.000000      0.000000      0.000000      2.000000      2.000000   
50%        4.000000      1.000000      0.000000      4.000000      2.000000   
75%        6.000000      1.000000      0.000000      4.000000      3.000000   
max        7.000000      1.000000      1.000000      4.000000      7.000000   

             T2_V15  
count  50999.000000  
mean       3.484480  
std        3.076745  
min        1.000000  
25%        1.000000  
50%        2.000000  
75%        5.000000  
max       12.000000  

[8 rows x 34 columns]

In [7]:
#stupid random forest
predictors=train.columns.values.tolist()[2:]

In [ ]:
test=pd.read_csv('test.csv')
for i in range(test.shape[1]):
    if test.iloc[:,i].dtype=='O':
        test.iloc[:,i]=le.fit_transform(test.iloc[:,i])

from sklearn.ensemble import RandomForestClassifier        
#alg = RandomForestClassifier(random_state=1, n_estimators=150, min_samples_split=4, min_samples_leaf=2)
alg = RandomForestClassifier()
alg.fit(train[predictors],train['Hazard'])
predictions=alg.predict(test[predictors])

submission = pd.DataFrame({
        "Id": test["Id"],
        "Hazard": predictions
    })

submission.to_csv("submission.csv", index=False)

In [39]:
# Simple implementation of the (normalized) gini score in numpy
# Fully vectorized, no python loops, zips, etc.
# Significantly (>30x) faster than previous implementions

import numpy as np 

def Gini(y_true, y_pred):
    # check and get number of samples
    assert y_true.shape == y_pred.shape
    n_samples = y_true.shape[0]
    
    # sort true values on prediction column 
    # (from largest to smallest)
    arr = np.array([y_true, y_pred]).transpose()
    true_order = arr[arr[:,0].argsort()][::-1,0]
    pred_order = arr[arr[:,1].argsort()][::-1,0]
    
    # get Lorenz curves
    L_true = np.cumsum(true_order) / np.sum(true_order)
    L_pred = np.cumsum(pred_order) / np.sum(pred_order)
    L_ones = np.linspace(1/n_samples, 1, n_samples)
    
    # get Gini coefficients (area between curves)
    G_true = np.sum(L_ones - L_true)
    G_pred = np.sum(L_ones - L_pred)
    
    # normalize to true Gini coefficient
    return G_pred/G_true

In [40]:
a=np.linspace(1,6,6)
b=np.linspace(14,9,6)
d = np.array([5.1, 3.2, 1.7, 6.2, 8.1])
p = np.array([3.1, 5.2, 2.7, 5.1, 1.1])
Gini(d,p)

[ 3.2  6.2  5.1  1.7  8.1]
[ 0.13168724  0.38683128  0.59670782  0.66666667  1.        ]
[ 0.2  0.4  0.6  0.8  1. ]


-0.3354430379746835

In [20]:
Gini(d,d)

[[ 5.1  5.1]
 [ 3.2  3.2]
 [ 1.7  1.7]
 [ 6.2  6.2]
 [ 8.1  8.1]]
[ 8.1  6.2  5.1  3.2  1.7]
[ 8.1  6.2  5.1  3.2  1.7]


1.0

In [28]:
def gini_ino(actual, pred, cmpcol = 0, sortcol = 1):
    assert( len(actual) == len(pred) )
    all = np.asarray(np.c_[ actual, pred, np.arange(len(actual)) ], dtype=np.float)
    print(all)
    all = all[ np.lexsort((all[:,2], -1*all[:,1])) ]
    print(all)
    totalLosses = all[:,0].sum()
    print(totalLosses)
    giniSum = all[:,0].cumsum().sum() / totalLosses
    giniSum -= (len(actual) + 1) / 2.
    return giniSum / len(actual)

def gini_normalized(a, p):
    return gini_ino(a, p) / gini_ino(a, a)

gini_normalized(d,p)

[[ 5.1  3.1  0. ]
 [ 3.2  5.2  1. ]
 [ 1.7  2.7  2. ]
 [ 6.2  5.1  3. ]
 [ 8.1  1.1  4. ]]
[[ 3.2  5.2  1. ]
 [ 6.2  5.1  3. ]
 [ 5.1  3.1  0. ]
 [ 1.7  2.7  2. ]
 [ 8.1  1.1  4. ]]
24.3
[[ 5.1  5.1  0. ]
 [ 3.2  3.2  1. ]
 [ 1.7  1.7  2. ]
 [ 6.2  6.2  3. ]
 [ 8.1  8.1  4. ]]
[[ 8.1  8.1  4. ]
 [ 6.2  6.2  3. ]
 [ 5.1  5.1  0. ]
 [ 3.2  3.2  1. ]
 [ 1.7  1.7  2. ]]
24.3


-0.33544303797468322